/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    CreatePost: typeof import('./src/components/post/CreatePost.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ProfileDropdown: typeof import('./src/components/navbar/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/navbar/SearchBar.vue')['default']
    TopNavigationBar: typeof import('./src/components/navbar/TopNavigationBar.vue')['default']
  }
}
