/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AddCar: typeof import('./src/components/car/AddCar.vue')['default']
    CreatePost: typeof import('./src/components/owner/CreatePost.vue')['default']
    EditCar: typeof import('./src/components/car/EditCar.vue')['default']
    EditProfile: typeof import('./src/components/profile/EditProfile.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LoginPage: typeof import('./src/components/AuthPage/LoginPage.vue')['default']
    OwnedProperties: typeof import('./src/components/owner/OwnedProperties.vue')['default']
    PostDetails: typeof import('./src/components/post/PostDetails.vue')['default']
    Posts: typeof import('./src/components/owner/Posts.vue')['default']
    Profile: typeof import('./src/components/profile/Profile.vue')['default']
    ProfileDropdown: typeof import('./src/components/navbar/ProfileDropdown.vue')['default']
    RegisterPage: typeof import('./src/components/AuthPage/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/navbar/SearchBar.vue')['default']
    Settings: typeof import('./src/components/profile/Settings.vue')['default']
    TopNavigationBar: typeof import('./src/components/navbar/TopNavigationBar.vue')['default']
    UserInfo: typeof import('./src/components/profile/UserInfo.vue')['default']
  }
}
