/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    ProfileDropdown: typeof import('./src/components/navbar/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/navbar/SearchBar.vue')['default']
    TopNavigationBar: typeof import('./src/components/navbar/TopNavigationBar.vue')['default']
  }
}
